# Generated by Django 4.2.1 on 2023-05-08 19:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organizationposition',
            old_name='title',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='organizationposition',
            name='user',
        ),
        migrations.CreateModel(
            name='TrainerPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.organizationposition')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='position', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
