# Generated by Django 4.2.1 on 2023-05-08 19:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0002_rename_title_organizationposition_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cohort',
            name='organization',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='organization.organization'),
            preserve_default=False,
        ),
    ]
