# Generated by Django 4.2.1 on 2023-05-08 19:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0003_cohort_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='stack',
            name='organization',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='stacks', to='organization.organization'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cohort',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cohorts', to='organization.organization'),
        ),
    ]
