# Generated by Django 4.2.1 on 2023-05-08 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0005_trainee_organization_trainer_organization'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainer',
            name='email',
        ),
        migrations.RemoveField(
            model_name='trainer',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='trainer',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='trainer',
            name='phone_number',
        ),
    ]
