# Generated by Django 4.2.1 on 2023-05-08 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0006_remove_trainer_email_remove_trainer_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainee',
            name='resume',
            field=models.FileField(upload_to='media/trainee/resume'),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='resume',
            field=models.FileField(upload_to='media/trainer/resume'),
        ),
    ]
