# Generated by Django 4.2.1 on 2023-05-09 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0007_alter_trainee_resume_alter_trainer_resume'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainee',
            name='email',
        ),
        migrations.RemoveField(
            model_name='trainee',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='trainee',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='trainee',
            name='phone_number',
        ),
    ]
