# Generated by Django 4.2.1 on 2023-05-09 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='approved',
        ),
        migrations.AddField(
            model_name='application',
            name='application_status',
            field=models.CharField(choices=[('A', 'Accepted'), ('D', 'Declined'), ('P', 'Pending')], default='P', max_length=1),
        ),
    ]
