# Generated by Django 4.2 on 2023-04-26 14:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='national_id',
            field=models.CharField(default=1, max_length=16, validators=[django.core.validators.RegexValidator('^[0-9]{16}$', 'Only 16-digit numeric values are allowed.')]),
            preserve_default=False,
        ),
    ]
