# Generated by Django 4.2 on 2023-04-28 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_user_national_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='national_id',
        ),
    ]
